### ISSUE TITLE
Is there a reason why kernel 4.14 is not used?

### ISSUE THREAD

**Issue by Hitman4** [Chippa-a/android_kernel_sony_msm8956#1]
Is there a reason why kernel 4.14 is not used?

https://developer.sony.com/file/download/software-binaries-for-aosp-android-10-0-kernel-4-14-loire

**Comment by Chippa-a** [comment]
You may have noticed that this kernel does not use SODP as a base. Anyway, 4.14 from SODP has not been finished and abandoned later.

I was managed to port kernel 4.19 and boot. It has some issues, but most likely it won't be completed as well as further overall development... due to the lack of community.
